// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfxlgikdearbrexlcvrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmeGxnaWtkZWFyYnJleGxjdnJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NzAwMzcsImV4cCI6MjA2MDM0NjAzN30.c8AnXvHENbDEpNTE8qMsUeVf-ur0u6DebVCmTLcydtc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);